version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: amanamart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: amanamart-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: amanamart-meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "${MEILISEARCH_MASTER_KEY}"
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meili_data:/meili_data

volumes:
  redis_data:
  rabbitmq_data:
  meili_data:
